import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "student dashboard",
    description: "Generated by create next app",
  };
  
  export default function StudentLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
        <>
        <div>{children}</div>
        </>
    )

  }