import type { Metadata } from "next";
import { AdminSidebar } from './_components/sidebar'
import { auth } from "@/auth";
import { redirect } from 'next/navigation'
export const metadata: Metadata = {
  title: "admin page",
  description: "Generated by create next app",
};

export default async function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  if(session?.user.role !== "ADMIN"){
redirect('/')
  }
  return (
    <>
      <div className="h-full flex gap-2">
        <AdminSidebar />
        {children}
        </div>
    </>
  );
}
